### ISSUE TITLE
How to catch the click on a paper-button?

### ISSUE THREAD

**Issue by a4xrbj1** [Code-Fights/blaze-material-ui#34]
I've created the following paper-button:

    {{#PaperButton elevated="true" className="delete"}}Remove{{/PaperButton}}

but now I'm stuck as to how I can catch the event of clicking on this button. The docs here are excellent but that part isn't addressed.

The "normal" spacebar method doesn't seem to work.

Any help is appreciated, both in an actual piece of code addressing my problem or pointing me towards an URL where I can read about it. Thanks!

**Comment by andyhqtran** [comment]
This will trigger and event on click. Is this what you're looking for?

```javascript 
Template.templateName.events({
  'click paper-button.delete': function (e) {
    $('.modal').hide();
  },
});
```

**Comment by a4xrbj1** [comment]
Yes Andy, that's what I was looking for. I still have to figure out what 

    $('.modal').hide();

is actually doing but that will keep me going again.

Can you point me to an URL where the various kinds of events that can happen with the paper-elements in this package are described and explained (for a beginner obviously)?

**Comment by andyhqtran** [comment]
The code I just put up there basically finds `.modal` element on `paper-button.delete` click and hides it.

`$('.modal').hide();` is [jQuery](http://api.jquery.com/hide/).

**Comment by a4xrbj1** [comment]
Unfortunately I still cannot catch the click event. I have created a public repo here: https://bitbucket.org/a4xrbj1/button/src

I've built the following two files:

button.html

    <head>
      <title>PaperButton click demo</title>
    </head>
    
    <body>
      {{#PaperButton elevated="true" className="delete"}}Remove{{/PaperButton}}
    </body>

button.js

    if (Meteor.isClient) {
        Template.body.events({
            'click paper-button.delete': function (e) {
                console.log('Delete button is clicked');
                $('.modal').hide();
            }
        });
    }

It never puts the console.log out, so I assume it never reaches there. Even if I put `test123();` instead of the `console.log` to make it crash there, it never does.

I'm puzzled as to how I can catch it. I've read through https://www.meteor.com/tutorials/blaze/forms-and-events but to no avail it seems. Thanks!

**Comment by andyhqtran** [comment]
Wrap your HTML code in a template tag.

**Comment by a4xrbj1** [comment]
Done that but I still see nothing on my screen:

<head>
  <title>PaperButton click demo</title>
</head>

<body>
</body>

<template name="Layout">
    {{#PaperButton elevated="true" className="delete"}}Remove{{/PaperButton}}
</template>

**Comment by HenriBeck** [comment]
you have to include the template in the body tag...

**Comment by andyhqtran** [comment]
@HenriBeck you don't even need the body tag. Meteor generates it for you.

@a4xrbj1 this is what it should look like.


```html
<template name="paperButton">
  {{#PaperButton className="delete" elevated="true"}}
    Remove
  {{/PaperButton}}
</template>
```

```JavaScript
if (Meteor.isClient) {
    Template.paperButton.events({
        'click paper-button.delete': function (e) {
            console.log('Button clicked.');
        }
    });
}
```

![image](https://cloud.githubusercontent.com/assets/6789067/11570501/66da3778-99ac-11e5-9c68-938a26be365a.png)

**Comment by HenriBeck** [comment]
yeah i know but if he includes the body tag in his code, he has to include the templates in it

**Comment by andyhqtran** [comment]
That's true, but in any case, he should just remove it.

**Comment by HenriBeck** [comment]
yeah

**Comment by a4xrbj1** [comment]
@andyhqtran I've copied your code exactly 1:1 into both files. In your last example the template wasn't called in the body section, so I added it. But the problem still remains the same, the JS for the click event isn't executed. I've tried it with debugging in WebStorm and also run it from the terminal (with adding a `test123();` statement which would make the app crash but to no avail.

There must be some other code missing.

Here's the repo at Bitbucket: https://bitbucket.org/a4xrbj1/button/

I'd like to invite everyone to try it for yourself. If I can't even get such a simple example like this going then using the package instead of Spacebars templates is completely obsolete.

I really would like to try the package out for my frontend.

**Comment by andyhqtran** [comment]
http://codefights.com <- Live Demo of it working.

I ran `meteor create build` and created a local version and then ran `meteor add codefights:blaze-material-ui`. Everything's added, changed the button to the paper button and bam, it works. It literally took 1min to set everything up. Link below.
itworksdude.meteor.com

`test123();` shouldn't be crashing the app. It only should throw an error because `test123();` isn't defined anywhere within your app.

![image](https://cloud.githubusercontent.com/assets/6789067/11584109/d10a66fe-9a15-11e5-83cd-0b27263c9d2a.png)

**Comment by a4xrbj1** [comment]
@andyhqtran I'm not saying that codefights or the codefights:blaze-material-ui package isn't working. My simple example which I put up on Bitbucket isn't working.

Would you mind sharing all the code with me for your http://itworksdude.meteor.com example?

I know **my mistake** lies somewhere between how I name the button and how I identify it in the click event.

**Comment by andyhqtran** [comment]
The code in that url is the exact same code I copied from the code in your repo with test123(); removed. None of the event handlers are broken.

**Comment by a4xrbj1** [comment]
Andy, the code that is running at: http://itworksdude.meteor.com/ is not
the same code as in my repo. That's the one I'm asking for.

My repo doesn't have the standard click and count example. Nor does my
example say "Welcome to Meteor".

I'm not sure what I have done that caused to upset you so much. I'm new to
front end development, still learning every day and even though I have no
problem with Spacebars templating language I can't get the same button with
your package to run.

So all I need to get going is one simple example that works and I can take
it from there. I'm 100% sure it's my fault but without a proper working
example I can't learn.

This thread has cost both of us already too much time. So I'd appreciate it
you could just copy the two source code files for your itworksdude example
here and we can close this issue.

Again, thank you!

**Comment by andyhqtran** [comment]
Check the console.
**EXACT** same code with just an `<h1>` tag and counter which doesn't effect it at all.

```html
<template name="paperButton">
  {{#PaperButton className="delete" elevated="true"}}
    Remove
  {{/PaperButton}}
</template>
```

```javascript
if (Meteor.isClient) {
    Template.paperButton.events({
        'click paper-button.delete': function (e) {
            console.log('Button clicked.');
        }
    });
}
```

**Comment by boxofrox** [comment]
@a4xrbj1, I just tested your example from the bitbucket repo and it worked.

```sh
$ cd /tmp
$ git clone https://bitbucket.org/a4xrbj1/button.git
$ cd button
$ meteor run
[[[[[ /tmp/button ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

- Open Chromium web browser (or Chrome)
- Visit http://localhost:3000/ (as directed by `meteor run` output)
- Open dev tools (Ctrl + Shift + I)
- Select dev tools console tab
- Click the Remove paper button
- Observe 'Button clicked.' in the browser console

I recommend you repeat these same steps yourself.  If it works, then compare these steps to your previously unsuccessful attempt to run the example, and see where you may have gone awry.

**Comment by a4xrbj1** [comment]
So both `click paper-button.delete` as well as `click .delete` are working and capturing the button click. Thanks to both of you for helping.

@boxofrox I'm not sure why it wasn't working before but as you suggested in the other package issue it might be something in my development that's not correct.
