### ISSUE TITLE
blaze-material-ui package cannot be added for Meteor version 1.1.0.3

### ISSUE THREAD

**Issue by a4xrbj1** [Code-Fights/blaze-material-ui#35]
Unfortunately I still need to develop in version 1.1.0.3 as WebStorm still hasn't fixed the errors that Meteor version 1.2 introduced. When I tried to add the package I've got the following two error messages:

    meteor add codefights:blaze-material-ui
    => Errors while adding packages:             
                                              
    While selecting package versions:
    error: unknown package: isobuild:isopack-2
    Required by: codefights:blaze-material-ui 0.1.7_2

    unknown package: isobuild:compiler-plugin
    Required by: ecmascript 0.1.3-plugins.1

**Comment by andyhqtran** [comment]
https://github.com/meteor/meteor/issues/5347#issuecomment-148074354

**Comment by a4xrbj1** [comment]
Understood @andyhqtran 

But that means that I cannot use your package for my project until WebStorm fixes all bugs related to Meteor version 1.2 (and so can't other developers).

Is it possible to build the package with version 1.1.0.3 or are you using any of the new ECMAscript (or other 1.2 features) in the package?

**Comment by andyhqtran** [comment]
This whole package revolves around ES6. 

Why are you using WebStrom as a development platform?

**Comment by a4xrbj1** [comment]
I'm using WebStorm as it's the only IDE for Meteor which allows me to do server-side debugging

**Comment by andyhqtran** [comment]
Meteor has built in debugging features. `meteor shell` and `meteor debug`.

**Comment by a4xrbj1** [comment]
I know and tried it. No comparison to using a real fully fledged IDE like WebStorm
